services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests

  obe:
    env_file: .env
    image: filkomunklab/obe-service:latest
    build: .
    ports:
      - "2001:2001"
    restart: always
